//SHOPS
# Crear una tienda con datos válidos
POST http://localhost:3001/api/shops
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NzA4MjU5MSwiZXhwIjoxNzQ3MDg2MTkxfQ.2PicyfATGWVKRhU1zbrwUY5u8mQHQedp1acMjUopOtY
Content-Type: application/json

{
  "ownerId": 2,
  "name": "Tienda de Deportes",
  "description": "Ropa y accesorios deportivos"
}

###

# Obtener todas las tiendas 
GET http://localhost:3001/api/shops

###

# Obtener una tienda por su ID (con categorías)
GET http://localhost:3001/api/shops/2

###

# Actualizar una tienda
PUT http://localhost:3001/api/shops/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJtYXJpYWciLCJyb2xlIjoic2FsZXNwZXJzb24iLCJpYXQiOjE3NDcwODMyMzksImV4cCI6MTc0NzA4NjgzOX0.3dEZdRs9sHE4bGkz6aCOQeYk2VmIKwX9NaZcjIPSH6E
Content-Type: application/json

{
  "ownerId": 1,
  "name": "Tienda de Deportes2",
  "description": "Ropa y accesorios deportivos"
}

###

# Eliminar una tienda por su ID (con categorías)
DELETE http://localhost:3001/api/shops/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJtYXJpYWciLCJyb2xlIjoic2FsZXNwZXJzb24iLCJpYXQiOjE3NDcwODI4MTMsImV4cCI6MTc0NzA4NjQxM30.D2KewR7TgP033smvIQwT93bxzR21NLtfnvDmYeZsx54
Content-Type: application/json

###

# Añadir una categoría a una tienda
POST http://localhost:3001/api/shops/2/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJtYXJpYWciLCJyb2xlIjoic2FsZXNwZXJzb24iLCJpYXQiOjE3NDcwODI4MTMsImV4cCI6MTc0NzA4NjQxM30.D2KewR7TgP033smvIQwT93bxzR21NLtfnvDmYeZsx54
Content-Type: application/json

{
  "categoryType": "Audio"
}

###

# Obtener las categorías de una tienda
GET http://localhost:3001/api/shops/2/categories

###

# Eliminar una categoría de una tienda
DELETE http://localhost:3001/api/shops/2/categories/Electrónica
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJtYXJpYWciLCJyb2xlIjoic2FsZXNwZXJzb24iLCJpYXQiOjE3NDcwODI4MTMsImV4cCI6MTc0NzA4NjQxM30.D2KewR7TgP033smvIQwT93bxzR21NLtfnvDmYeZsx54
Content-Type: application/json

###