# Crear un pedido nuevo con productos nuevos
POST http://localhost:3001/api/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJqdWFucCIsInJvbGUiOiJzaG9wcGVyIiwiaWF0IjoxNzQ3MDc2Njg3LCJleHAiOjE3NDcwODAyODd9.1Dxv-pEOQO6UnnOePRyRXqdXwLiLtU-8G36B_YrnEoo

{
  "shopperId": 1,
  "shopId": 1,
  "address": "Calle Nueva 99",
  "status": "pending",
  "totalPrice": 49.99,
  "products": [
    {
      "productId": 4,
      "quantity": 1,
      "totalProductPrice": 49.99
    }
  ]
}

###

# Obtener todos los pedidos (mariag)
GET http://localhost:3001/api/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJqdWFucCIsInJvbGUiOiJzaG9wcGVyIiwiaWF0IjoxNzQ4MzU1Njc0LCJleHAiOjE3NDgzNTkyNzR9.hE0Ry6CT9tvZUyRtZPXunuMJ1KTy3bO2ajxkIPWapqU

# Obtener un pedido por ID
GET http://localhost:3001/api/order/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJtYXJpYWciLCJyb2xlIjoic2FsZXNwZXJzb24iLCJpYXQiOjE3NDcwODU2NTcsImV4cCI6MTc0NzA4OTI1N30.ovPfw1f_axQnNmQbwNdX86LopbyU8yNKGsyQ8PAOvj4


###

# Actualizar un pedido
PUT http://localhost:3001/api/order/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJqdWFucCIsInJvbGUiOiJzaG9wcGVyIiwiaWF0IjoxNzQ3MDg2MTkyLCJleHAiOjE3NDcwODk3OTJ9.uXsOSojeJmaZCUey_HON576n9PQ-17NMBrlsiEJ3JBk
Content-Type: application/json

{
  "status": "shipped"
}

###

# Eliminar un pedido
DELETE http://localhost:3001/api/order/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJtYXJpYWciLCJyb2xlIjoic2FsZXNwZXJzb24iLCJpYXQiOjE3NDcwODU2NTcsImV4cCI6MTc0NzA4OTI1N30.ovPfw1f_axQnNmQbwNdX86LopbyU8yNKGsyQ8PAOvj4


###



