GET http://localhost:3001/api/users

###

GET http://localhost:3001/api/users/1

###

DELETE http://localhost:3001/api/users/1

###

# Crear usuario
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Admin",
  "username": "admin2",
  "password": "admin1234",
  "email": "user1@gmail.com",
  "role": "admin"
}

###

# Crear usuario con username duplicado (debe fallar)
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Carlos López",
  "username": "admin",
  "password": "admin1234",
  "email": "carlos@example.com",
  "role": "admin"
}

###

# Obtener usuario inexistente (debe fallar)
GET http://localhost:3001/api/users/99999

###

# Actualizar usuario con datos válidos
PUT http://localhost:3001/api/users/1
Content-Type: application/json

{
  "name": "Carlos López",
  "username": "admin",
  "email": "carlos@example.com",
  "role": "admin",
  "passwordActual": "admin1234",
  "newPassword": "admin12345"
}

###

# Intentar actualizar usuario con contraseña incorrecta (debe fallar)
PUT http://localhost:3001/api/users/1
Content-Type: application/json

{
  "name": "New Name",
  "username": "newUsername",
  "email": "new@example.com",
  "role": "admin",
  "passwordActual": "wrongPassword",
  "newPassword": "newSecret123"
}

###

# Intentar eliminar usuario inexistente (debe fallar)
DELETE http://localhost:3001/api/users/99999


###

# Login Admin con datos válidos
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin1234"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "mariag",
  "password": "1234"
}
