//SHOPS
# Crear una tienda con datos válidos
POST http://localhost:3001/api/shops
Content-Type: application/json

{
  "ownerId": 4,
  "name": "Tienda de Deportes",
  "description": "Ropa y accesorios deportivos"
}

###

# Create 
POST http://localhost:3001/api/shops
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjMsImlhdCI6MTc0Mjc2MDU4M30.XhXfX1Xvk_VPrCZvKvQohieEann_nuLm0WK4gekKiRw
Content-Type: application/json

{
  "ownerId": 2,
  "name": "Tienda de ropa",
  "description": "Ropa de moda",
}

###

# Obtener todas las tiendas
GET http://localhost:3001/api/shops

###

# Obtener una tienda por su ID (con categorías)
GET http://localhost:3001/api/shops/1

###

# Añadir una categoría a una tienda
POST http://localhost:3001/api/shops/2/categories
Content-Type: application/json

{
  "categoryType": "Audio"
}

###

# Obtener las categorías de una tienda
GET http://localhost:3001/api/shops/2/categories

###

# Eliminar una categoría de una tienda
DELETE http://localhost:3001/api/shops/2/categories/Audio

###

# Crear una tienda con datos inválidos (debe fallar)
POST http://localhost:3001/api/shops
Content-Type: application/json

{
  "name": "Tienda de Zapatos"
}

###

# Obtener una tienda inexistente (debe fallar)
GET http://localhost:3001/api/shops/9999

###

# Eliminar una tienda
DELETE http://localhost:3001/api/shops/2

###

# Eliminar una tienda inexistente (debe fallar)
DELETE http://localhost:3001/api/shops/9999
