// PRODUCTS


# Crear un producto nuevo para Tienda de María (shopId = 1)
POST http://localhost:3001/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJtYXJpYWciLCJyb2xlIjoic2FsZXNwZXJzb24iLCJpYXQiOjE3NDcwODQyMjAsImV4cCI6MTc0NzA4NzgyMH0.hBpys9b0yLZSjOUT39RJgh11IfMUR0YiM0teoZF8QuM

{
  "shopId": 1,
  "name": "Chaqueta Roja",
  "description": "Chaqueta impermeable con forro polar",
  "price": 49.99,
  "size": "L"
}

###


# Obtener todos los productos
GET http://localhost:3001/api/products

###

# Obtener un producto por su ID con imágenes
GET http://localhost:3001/api/products/1

###

# Actualizar un producto
PUT http://localhost:3001/api/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJtYXJpYWciLCJyb2xlIjoic2FsZXNwZXJzb24iLCJpYXQiOjE3NDcwODQyMjAsImV4cCI6MTc0NzA4NzgyMH0.hBpys9b0yLZSjOUT39RJgh11IfMUR0YiM0teoZF8QuM
Content-Type: application/json

{
  "name": "Camiseta Deportiva (Nuevo Diseño)",
  "shopId": 1,
  "description": "Camiseta deportiva de alta calidad, nuevo diseño",
  "price": 29.99,
  "size": "M"
}

###

# Eliminar un producto por ID
DELETE http://localhost:3001/api/products/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJtYXJpYWciLCJyb2xlIjoic2FsZXNwZXJzb24iLCJpYXQiOjE3NDcwODQyMjAsImV4cCI6MTc0NzA4NzgyMH0.hBpys9b0yLZSjOUT39RJgh11IfMUR0YiM0teoZF8QuM
Content-Type: application/json
###

// PRODUCT IMAGES

# Agregar una imagen a un producto
POST http://localhost:3001/api/products/1/images
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJtYXJpYWciLCJyb2xlIjoic2FsZXNwZXJzb24iLCJpYXQiOjE3NDcwODQyMjAsImV4cCI6MTc0NzA4NzgyMH0.hBpys9b0yLZSjOUT39RJgh11IfMUR0YiM0teoZF8QuM
Content-Type: application/json

{
  "imageUrl": "http://example.com/images/camiseta.jpg"
}

###

# Obtener todas las imágenes de un producto
GET http://localhost:3001/api/products/1/images

###

# Eliminar todas las imágenes de un producto
DELETE http://localhost:3001/api/products/1/images
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJtYXJpYWciLCJyb2xlIjoic2FsZXNwZXJzb24iLCJpYXQiOjE3NDcwODQyMjAsImV4cCI6MTc0NzA4NzgyMH0.hBpys9b0yLZSjOUT39RJgh11IfMUR0YiM0teoZF8QuM


###
